INSERT INTO `ref_bureau` VALUES(1, 'BAC', 'Bureau Afrique centrale', 'Afrique centrale', 'Bureau Afrique centrale', 11, 1, 1);
INSERT INTO `ref_bureau` VALUES(2, 'BAO', 'Bureau Afrique de l''Ouest', 'Afrique de l''Ouest', 'Bureau Afrique de l''Ouest', 43, 2, 1);
INSERT INTO `ref_bureau` VALUES(3, 'BAP', 'Bureau Asie-Pacifique', 'Asie-Pacifique', 'Bureau Asie-Pacifique', 51, 4, 1);
INSERT INTO `ref_bureau` VALUES(4, 'BC', 'Bureau Caraïbe', 'Caraïbe', 'Bureau Caraïbe', 22, 5, 1);
INSERT INTO `ref_bureau` VALUES(5, 'BECO', 'Bureau Europe centrale et orientale', 'Europe centrale & o.', 'Bureau Europe centrale et orientale', 41, 6, 1);
INSERT INTO `ref_bureau` VALUES(6, 'BEOM', 'Bureau Europe de l''Ouest et Maghreb', 'Europe de l''Ouest&M.', 'Bureau Europe de l''Ouest et Maghreb', 18, 7, 1);
INSERT INTO `ref_bureau` VALUES(7, 'BMO', 'Bureau Moyen-Orient', 'Moyen-Orient', 'Bureau Moyen-Orient', 26, 8, 1);
INSERT INTO `ref_bureau` VALUES(8, 'BOI', 'Bureau Océan indien', 'Océan indien', 'Bureau Océan indien', 27, 9, 1);
INSERT INTO `ref_bureau` VALUES(9, 'BSC', 'Services centraux', 'Services centraux', 'Services centraux', 0, 0, 1);
INSERT INTO `ref_bureau` VALUES(10, 'BA', 'Bureau des Amériques', 'Amériques', 'Bureau des Amériques', 14, 3, 1);
