INSERT INTO `ref_discipline` VALUES(1, 'D10', 'Sciences de la vie', 'Sciences de la vie', 'Sciences de la vie', 1);
INSERT INTO `ref_discipline` VALUES(2, 'D11', 'Santé et recherche biomédicale : biologie, épidémiologie, pathologies, thérapeutiques', 'Santé recherche biomédicale', 'Santé biomédicale', 1);
INSERT INTO `ref_discipline` VALUES(3, 'D12', 'Biologie animale et recherches vétérinaires : biologie, génétique, nutrition, élevage, épidémiologie, pathologies, thérapeutiques', 'Biologie animale recherche véto', 'Biol animale véto', 1);
INSERT INTO `ref_discipline` VALUES(4, 'D13', 'Biologie végétale et recherches agronomiques : biologie, génétique et amélioration des plantes, épidémiologie, pathologies, thérapeutiques', 'Biologie végétale recherches agro', 'Biologie végétale', 1);
INSERT INTO `ref_discipline` VALUES(5, 'D20', 'Sciences de la matière', 'Sciences de la matière', 'Sciences matière', 1);
INSERT INTO `ref_discipline` VALUES(6, 'D21', 'Sciences physiques et mathématiques', 'Sciences physiques math', 'Physique math', 1);
INSERT INTO `ref_discipline` VALUES(7, 'D22', 'Sciences chimiques', 'Sciences chimiques', 'Sc Chimie', 1);
INSERT INTO `ref_discipline` VALUES(8, 'D23', 'Sciences de l''Univers : astronomie, astrophysique, océan, atmosphère, sciences de la terre', 'Sciences Univers', 'Sc Univers', 1);
INSERT INTO `ref_discipline` VALUES(9, 'D30', 'Sciences pour l''ingénieur', 'Sciences pour l''ingénieur', 'Sciences ingénieur', 1);
INSERT INTO `ref_discipline` VALUES(10, 'D31', 'Connaissance et gestion des ressources naturelles : eau, sol, biodiversité, en relation avec les activités humaines (environnement-développement)', 'Connaissance gestion ressources nat', 'Ress naturelles', 1);
INSERT INTO `ref_discipline` VALUES(11, 'D32', 'Agro-alimentaire et Génie des Procédés : transformation des produits animaux et végétaux', 'Agro alimentaire génie procédés', 'Agro alimentaire', 1);
INSERT INTO `ref_discipline` VALUES(12, 'D33', 'Télédétection et applications', 'Télédétection applications', 'Télédétection', 1);
INSERT INTO `ref_discipline` VALUES(13, 'D34', 'Electronique et Génie électrique', 'Electronique génie elec', 'Electronique', 1);
INSERT INTO `ref_discipline` VALUES(14, 'D35', 'Mécanique et Génie des Matériaux', 'Mécanique génie matériaux', 'Mécanique', 1);
INSERT INTO `ref_discipline` VALUES(15, 'D36', 'Energie et Génie des Procédés', 'Energie génie procédés', 'Procédés', 1);
INSERT INTO `ref_discipline` VALUES(16, 'D37', 'Génie linguistique', 'Génie linguistique', 'Linguistique', 1);
INSERT INTO `ref_discipline` VALUES(17, 'D38', 'Sciences et Technologies de l''Information et de la Communication : informatique, automatique, traitement du signal, sciences de l''information', 'Sciences techno infor comm', 'Info comm', 1);
INSERT INTO `ref_discipline` VALUES(18, 'D40', 'Sciences de l''Homme et de la société', 'Sciences de l''Homme et de la société', 'Sciences H et Soc', 1);
INSERT INTO `ref_discipline` VALUES(19, 'D41', 'Langues et Humanités : sciences du langage, littérature, philosophie, sciences historiques, pédagogie', 'Langues humanités', 'Humanités', 1);
INSERT INTO `ref_discipline` VALUES(20, 'D42', 'Sciences économiques', 'Sciences économiques', 'Economie', 1);
INSERT INTO `ref_discipline` VALUES(21, 'D43', 'Sciences de gestion', 'Sciences gestion', 'Gestion', 1);
INSERT INTO `ref_discipline` VALUES(22, 'D44', 'Sociologie : démographie', 'Sociologie', 'Sociologie', 1);
INSERT INTO `ref_discipline` VALUES(23, 'D45', 'Anthropologie', 'Anthropologie', 'Anthropologie', 1);
INSERT INTO `ref_discipline` VALUES(24, 'D46', 'Sciences juridiques : droits publics, droits fondamentaux', 'Sciences juridiques fondamentaux', 'Droit fondamentaux', 1);
INSERT INTO `ref_discipline` VALUES(25, 'D47', 'Sciences juridiques : droit de l''environnement', 'Sciences juridiques environnement', 'Droit environnement', 1);
INSERT INTO `ref_discipline` VALUES(26, 'D48', 'Science politique', 'Sciences politiques', 'Sc politiques', 1);
INSERT INTO `ref_discipline` VALUES(27, 'D49', 'Géographie et aménagement : villes, urbanisme, transport', 'Géographie aménagement', 'Géographie', 1);
INSERT INTO `ref_discipline` VALUES(28, 'D98', 'Multidisciplinaire', 'Multidisciplinaire', 'Multidisciplinaire', 1);
INSERT INTO `ref_discipline` VALUES(29, 'D99', 'Autre discipline', 'Autre discipline', 'Autre discipline', 1);
INSERT INTO `ref_discipline` VALUES(30, 'D51', 'Sciences juridiques : droit privé et des affaires', 'Sciences juridiques privé & affaires', 'Droit privé & affair', 1);
INSERT INTO `ref_discipline` VALUES(31, 'D52', 'Sciences du tourisme', 'Sciences du tourisme', 'Sciences Tourisme', 1);
