
INSERT INTO `ref_pays` VALUES(1, 'AD', 'AND', 'Andorre', 7, 'BEOM', 'Nord', 'Elevé', 'euro', 1);
INSERT INTO `ref_pays` VALUES(2, 'AE', 'ARE', 'Émirats arabes unis', 8, 'BMO', 'Nord', 'Elevé', 'dirham ÉAU', 1);
INSERT INTO `ref_pays` VALUES(3, 'AF', 'AFG', 'Afghanistan', 8, 'BMO', 'Sud', 'Faible', 'afghani', 1);
INSERT INTO `ref_pays` VALUES(4, 'AG', 'ATG', 'Antigua Et Barbuda', 5, 'BC', 'Nord', 'Elevé', 'dollar des Caraïbes de l''Est', 1);
INSERT INTO `ref_pays` VALUES(5, 'AL', 'ALB', 'Albanie', 6, 'BECO', 'Sud', 'Moyen', 'lek', 1);
INSERT INTO `ref_pays` VALUES(6, 'AM', 'ARM', 'Arménie', 6, 'BECO', 'Sud', 'Moyen', 'dram', 1);
INSERT INTO `ref_pays` VALUES(7, 'AO', 'AGO', 'Angola', 1, 'BAC', 'Sud', 'Moyen', 'kwanza', 1);
INSERT INTO `ref_pays` VALUES(8, 'AR', 'ARG', 'Argentine', 3, 'BA', 'Sud', 'Moyen', '9 juillet (Indépendance en 1816))"', 1);
INSERT INTO `ref_pays` VALUES(9, 'AT', 'AUT', 'Autriche', 7, 'BEOM', 'Nord', 'Elevé', 'euro', 1);
INSERT INTO `ref_pays` VALUES(10, 'AU', 'AUS', 'Australie', 4, 'BAP', 'Nord', 'Elevé', 'dollar australien', 1);
INSERT INTO `ref_pays` VALUES(11, 'AZ', 'AZE', 'Azerbaïdjan', 6, 'BECO', 'Sud', 'Moyen', 'manat azéri', 1);
INSERT INTO `ref_pays` VALUES(12, 'BA', 'BIH', 'Bosnie-Herzégovine', 6, 'BECO', 'Sud', 'Moyen', 'mark bosniaque convertible', 1);
INSERT INTO `ref_pays` VALUES(13, 'BB', 'BRB', 'Barbade', 5, 'BC', 'Nord', 'Elevé', 'dollar de la Barbade', 1);
INSERT INTO `ref_pays` VALUES(14, 'BD', 'BGD', 'Bangladesh', 4, 'BAP', 'Sud', 'Faible', 'taka', 1);
INSERT INTO `ref_pays` VALUES(15, 'BE', 'BEL', 'Belgique', 7, 'BEOM', 'Nord', 'Elevé', 'euro', 1);
INSERT INTO `ref_pays` VALUES(16, 'BF', 'BFA', 'Burkina Faso', 2, 'BAO', 'Sud', 'Faible', 'franc C.F.A', 1);
INSERT INTO `ref_pays` VALUES(17, 'BG', 'BGR', 'Bulgarie', 6, 'BECO', 'Sud', 'Moyen', 'lev', 1);
INSERT INTO `ref_pays` VALUES(18, 'BH', 'BHR', 'Bahreïn', 8, 'BMO', 'Nord', 'Elevé', 'dinar de Barhreïn', 1);
INSERT INTO `ref_pays` VALUES(19, 'BI', 'BDI', 'Burundi', 1, 'BAC', 'Sud', 'Faible', 'franc burundais', 1);
INSERT INTO `ref_pays` VALUES(20, 'BJ', 'BEN', 'Bénin', 2, 'BAO', 'Sud', 'Faible', 'franc C.F.A', 1);
INSERT INTO `ref_pays` VALUES(21, 'BN', 'BRN', 'Brunéi Darussalam', 4, 'BAP', 'Nord', 'Elevé', 'dollar de Brunei', 1);
INSERT INTO `ref_pays` VALUES(22, 'BO', 'BOL', 'Bolivie', 3, 'BA', 'Sud', 'Moyen', 'boliviano', 1);
INSERT INTO `ref_pays` VALUES(23, 'BR', 'BRA', 'Brésil', 3, 'BA', 'Sud', 'Moyen', 'real brésilien', 1);
INSERT INTO `ref_pays` VALUES(24, 'BS', 'BHS', 'Bahamas', 5, 'BC', 'Nord', 'Elevé', 'dollar des Bahamas', 1);
INSERT INTO `ref_pays` VALUES(25, 'BT', 'BTN', 'Bhoutan', 4, 'BAP', 'Sud', 'Moyen', 'ngultrum', 1);
INSERT INTO `ref_pays` VALUES(26, 'BW', 'BWA', 'Botswana', 1, 'BAC', 'Sud', 'Moyen', 'pula', 1);
INSERT INTO `ref_pays` VALUES(27, 'BY', 'BLR', 'Bélarus', 6, 'BECO', 'Sud', 'Moyen', 'rouble biélorusse', 1);
INSERT INTO `ref_pays` VALUES(28, 'BZ', 'BLZ', 'Belize', 3, 'BA', 'Sud', 'Moyen', 'dollar de Bélize', 1);
INSERT INTO `ref_pays` VALUES(29, 'CA', 'CAN', 'Canada', 3, 'BA', 'Nord', 'Elevé', 'dollar canadien', 1);
INSERT INTO `ref_pays` VALUES(30, 'CD', 'COD', 'Congo, la république démocratique du', 1, 'BAC', 'Sud', 'Faible', 'Paix, justice, travail', 1);
INSERT INTO `ref_pays` VALUES(31, 'CF', 'CAF', 'Centrafricaine, république', 1, 'BAC', 'Sud', 'Faible', 'franc C.F.A', 1);
INSERT INTO `ref_pays` VALUES(32, 'CG', 'COG', 'Congo', 1, 'BAC', 'Sud', 'Moyen', 'franc C.F.A', 1);
INSERT INTO `ref_pays` VALUES(33, 'CH', 'CHE', 'Suisse', 7, 'BEOM', 'Nord', 'Elevé', 'franc suisse', 1);
INSERT INTO `ref_pays` VALUES(34, 'CI', 'CIV', 'Côte d''Ivoire', 2, 'BAO', 'Sud', 'Faible', 'franc C.F.A', 1);
INSERT INTO `ref_pays` VALUES(35, 'CL', 'CHL', 'Chili', 3, 'BA', 'Sud', 'Moyen', 'peso chilien', 1);
INSERT INTO `ref_pays` VALUES(36, 'CM', 'CMR', 'Cameroun', 1, 'BAC', 'Sud', 'Moyen', 'franc C.F.A', 1);
INSERT INTO `ref_pays` VALUES(37, 'CN', 'CHN', 'Chine', 4, 'BAP', 'Sud', 'Moyen', 'yuan renminbi', 1);
INSERT INTO `ref_pays` VALUES(38, 'CO', 'COL', 'Colombie', 3, 'BA', 'Sud', 'Moyen', 'peso colombien', 1);
INSERT INTO `ref_pays` VALUES(39, 'CR', 'CRI', 'Costa Rica', 3, 'BA', 'Sud', 'Moyen', 'colon du Costa Rica', 1);
INSERT INTO `ref_pays` VALUES(40, 'CS', 'SCG', 'Serbie-Monténégro (cf. scission)', 0, 'BECO', 'Sud', 'Faible', 'dinar yougoslave', 1);
INSERT INTO `ref_pays` VALUES(41, 'CU', 'CUB', 'Cuba', 5, 'BC', 'Sud', 'Moyen', 'peso cubain', 1);
INSERT INTO `ref_pays` VALUES(42, 'CV', 'CPV', 'Cap-Vert', 2, 'BAO', 'Sud', 'Moyen', 'escudo du Cap-Vert', 1);
INSERT INTO `ref_pays` VALUES(43, 'CY', 'CYP', 'Chypre', 6, 'BECO', 'Nord', 'Elevé', 'livre chypriote', 1);
INSERT INTO `ref_pays` VALUES(44, 'CZ', 'CZE', 'Tchèque, république', 6, 'BECO', 'Nord', 'Elevé', 'couronne tchèque', 1);
INSERT INTO `ref_pays` VALUES(45, 'DE', 'DEU', 'Allemagne', 7, 'BEOM', 'Nord', 'Elevé', 'euro', 1);
INSERT INTO `ref_pays` VALUES(46, 'DJ', 'DJI', 'Djibouti', 8, 'BMO', 'Sud', 'Moyen', 'franc de Djibouti', 1);
INSERT INTO `ref_pays` VALUES(47, 'DK', 'DNK', 'Danemark', 7, 'BEOM', 'Nord', 'Elevé', 'couronne danoise', 1);
INSERT INTO `ref_pays` VALUES(48, 'DM', 'DMA', 'Dominique', 5, 'BC', 'Sud', 'Moyen', 'dollar des Caraïbes de l''Est', 1);
INSERT INTO `ref_pays` VALUES(49, 'DO', 'DOM', 'Dominicaine, république', 5, 'BC', 'Sud', 'Moyen', 'peso dominicain', 1);
INSERT INTO `ref_pays` VALUES(50, 'DZ', 'DZA', 'Algérie', 7, 'BEOM', 'Sud', 'Moyen', 'dinar algérien', 1);
INSERT INTO `ref_pays` VALUES(51, 'UZ', 'UZB', 'Ouzbékistan', 6, 'BECO', 'Sud', 'Faible', 'sum d''Ouzbékistan', 1);
INSERT INTO `ref_pays` VALUES(52, 'UY', 'URY', 'Uruguay', 3, 'BA', 'Sud', 'Moyen', 'peso uruguayen', 1);
INSERT INTO `ref_pays` VALUES(53, 'US', 'USA', 'États-Unis', 3, 'BA', 'Nord', 'Elevé', 'Tous"', 1);
INSERT INTO `ref_pays` VALUES(54, 'UG', 'UGA', 'Ouganda', 1, 'BAC', 'Sud', 'Faible', 'shilling ougandais', 1);
INSERT INTO `ref_pays` VALUES(55, 'UA', 'UKR', 'Ukraine', 6, 'BECO', 'Sud', 'Moyen', 'grivna', 1);
INSERT INTO `ref_pays` VALUES(56, 'TZ', 'TZA', 'Tanzanie, république-unie de', 9, 'BOI', 'Sud', 'Faible', 'shilling tanzanien', 1);
INSERT INTO `ref_pays` VALUES(57, 'TV', 'TUV', 'Tuvalu', 4, 'BAP', 'Sud', 'Moyen', 'dollar australien', 1);
INSERT INTO `ref_pays` VALUES(58, 'TT', 'TTO', 'Trinité-et-Tobago', 5, 'BC', 'Nord', 'Elevé', 'dollar de Trinité-et-Tobago', 1);
INSERT INTO `ref_pays` VALUES(59, 'TO', 'TON', 'Tonga', 4, 'BAP', 'Sud', 'Moyen', 'pa''anga', 1);
INSERT INTO `ref_pays` VALUES(60, 'TR', 'TUR', 'Turquie', 6, 'BECO', 'Sud', 'Moyen', 'lire turque', 1);
INSERT INTO `ref_pays` VALUES(61, 'TN', 'TUN', 'Tunisie', 7, 'BEOM', 'Sud', 'Moyen', 'dinar tunisien', 1);
INSERT INTO `ref_pays` VALUES(62, 'TL', 'TLS', 'Timor-Leste', 4, 'BAP', 'Sud', 'Moyen', 'None', 1);
INSERT INTO `ref_pays` VALUES(63, 'TM', 'TKM', 'Turkménistan', 6, 'BECO', 'Sud', 'Moyen', 'manat turkmène', 1);
INSERT INTO `ref_pays` VALUES(64, 'TJ', 'TJK', 'Tadjikistan', 6, 'BECO', 'Sud', 'Faible', 'somoni', 1);
INSERT INTO `ref_pays` VALUES(65, 'TH', 'THA', 'Thaïlande', 4, 'BAP', 'Sud', 'Moyen', 'baht', 1);
INSERT INTO `ref_pays` VALUES(66, 'TG', 'TGO', 'Togo', 2, 'BAO', 'Sud', 'Faible', 'franc C.F.A.', 1);
INSERT INTO `ref_pays` VALUES(67, 'TD', 'TCD', 'Tchad', 1, 'BAC', 'Sud', 'Faible', 'franc C.F.A.', 1);
INSERT INTO `ref_pays` VALUES(68, 'SZ', 'SWZ', 'Swaziland', 1, 'BAC', 'Sud', 'Moyen', 'lilangeni', 1);
INSERT INTO `ref_pays` VALUES(69, 'SY', 'SYR', 'Syrienne, république arabe', 8, 'BMO', 'Sud', 'Moyen', 'livre syrienne', 1);
INSERT INTO `ref_pays` VALUES(70, 'SV', 'SLV', 'El Salvador', 3, 'BA', 'Sud', 'Moyen', 'colon du Salvador', 1);
INSERT INTO `ref_pays` VALUES(71, 'ST', 'STP', 'Sao Tomé-et-Principe', 1, 'BAC', 'Sud', 'Faible', 'dobra', 1);
INSERT INTO `ref_pays` VALUES(72, 'SR', 'SUR', 'Suriname', 3, 'BA', 'Sud', 'Moyen', 'florin du Suriname', 1);
INSERT INTO `ref_pays` VALUES(73, 'SN', 'SEN', 'Sénégal', 2, 'BAO', 'Sud', 'Faible', 'franc C.F.A.', 1);
INSERT INTO `ref_pays` VALUES(74, 'SO', 'SOM', 'Somalie', 1, 'BAC', 'Sud', 'Faible', 'None', 1);
INSERT INTO `ref_pays` VALUES(75, 'SM', 'SMR', 'Saint-Marin', 7, 'BEOM', 'Nord', 'Elevé', 'euro', 1);
INSERT INTO `ref_pays` VALUES(76, 'SL', 'SLE', 'Sierra Leone', 2, 'BAO', 'Sud', 'Faible', 'leone', 1);
INSERT INTO `ref_pays` VALUES(77, 'SK', 'SVK', 'Slovaquie', 6, 'BECO', 'Nord', 'Elevé', 'couronne slovaque', 1);
INSERT INTO `ref_pays` VALUES(78, 'SI', 'SVN', 'Slovénie', 6, 'BECO', 'Nord', 'Elevé', 'tolar slovène', 1);
INSERT INTO `ref_pays` VALUES(79, 'SG', 'SGP', 'Singapour', 4, 'BAP', 'Nord', 'Elevé', 'dollar de Singapour', 1);
INSERT INTO `ref_pays` VALUES(80, 'SE', 'SWE', 'Suède', 7, 'BEOM', 'Nord', 'Elevé', 'couronne suédoise', 1);
INSERT INTO `ref_pays` VALUES(81, 'SD', 'SDN', 'Soudan', 1, 'BAC', 'Sud', 'Moyen', 'dinar soudanais', 1);
INSERT INTO `ref_pays` VALUES(82, 'SB', 'SLB', 'Salomon, îles', 4, 'BAP', 'Sud', 'Faible', 'dollar des Iles Salomon', 1);
INSERT INTO `ref_pays` VALUES(83, 'SC', 'SYC', 'Seychelles', 9, 'BOI', 'Sud', 'Moyen', 'None', 1);
INSERT INTO `ref_pays` VALUES(84, 'SA', 'SAU', 'Arabie Saoudite', 8, 'BMO', 'Nord', 'Elevé', 'riyal saoudien', 1);
INSERT INTO `ref_pays` VALUES(85, 'RW', 'RWA', 'Rwanda', 1, 'BAC', 'Sud', 'Faible', 'franc rwandais', 1);
INSERT INTO `ref_pays` VALUES(86, 'S3', 'S33', 'Sans objet', 0, 'BXX', 'None', 'inconnu', 'None', 1);
INSERT INTO `ref_pays` VALUES(87, 'RU', 'RUS', 'Russie, fédération de', 6, 'BECO', 'Sud', 'Moyen', 'rouble russe', 1);
INSERT INTO `ref_pays` VALUES(88, 'RO', 'ROU', 'Roumanie', 6, 'BECO', 'Sud', 'Moyen', 'leu roumain', 1);
INSERT INTO `ref_pays` VALUES(89, 'QA', 'QAT', 'Qatar', 8, 'BMO', 'Nord', 'Elevé', 'rial du Qatar', 1);
INSERT INTO `ref_pays` VALUES(90, 'PY', 'PRY', 'Paraguay', 3, 'BA', 'Sud', 'Moyen', 'guarani', 1);
INSERT INTO `ref_pays` VALUES(91, 'PW', 'PLW', 'Palaos', 4, 'BAP', 'Sud', 'Moyen', 'dollar US', 1);
INSERT INTO `ref_pays` VALUES(92, 'PT', 'PRT', 'Portugal', 7, 'BEOM', 'Nord', 'Elevé', 'Le bien de la nation (O bem da Nação)', 1);
INSERT INTO `ref_pays` VALUES(93, 'PS', 'PSE', 'Palestinien Occupé, Territoire', 8, 'BMO', 'Sud', 'Moyen', 'Livre palestinienne', 1);
INSERT INTO `ref_pays` VALUES(94, 'PL', 'POL', 'Pologne', 6, 'BECO', 'Sud', 'Moyen', 'zloty', 1);
INSERT INTO `ref_pays` VALUES(95, 'PK', 'PAK', 'Pakistan', 8, 'BMO', 'Sud', 'Faible', 'roupie pakistanaise', 1);
INSERT INTO `ref_pays` VALUES(96, 'PH', 'PHL', 'Philippines', 4, 'BAP', 'Sud', 'Moyen', 'peso philippin', 1);
INSERT INTO `ref_pays` VALUES(97, 'PG', 'PNG', 'Papouasie-Nouvelle-Guinée', 4, 'BAP', 'Sud', 'Faible', 'kina', 1);
INSERT INTO `ref_pays` VALUES(98, 'PE', 'PER', 'Pérou', 3, 'BA', 'Sud', 'Moyen', 'nouveau sol', 1);
INSERT INTO `ref_pays` VALUES(99, 'OM', 'OMN', 'Oman', 8, 'BMO', 'Nord', 'Elevé', 'riyal d''Oman', 1);
INSERT INTO `ref_pays` VALUES(100, 'PA', 'PAN', 'Panama', 3, 'BA', 'Sud', 'Moyen', 'balboa', 1);
INSERT INTO `ref_pays` VALUES(101, 'NZ', 'NZL', 'Nouvelle-Zélande', 4, 'BAP', 'Nord', 'Elevé', 'dollar néo-zélandais', 1);
INSERT INTO `ref_pays` VALUES(102, 'NR', 'NRU', 'Nauru', 4, 'BAP', 'Sud', 'Moyen', 'dollar australien', 1);
INSERT INTO `ref_pays` VALUES(103, 'NP', 'NPL', 'Népal', 4, 'BAP', 'Sud', 'Faible', 'roupie népalaise', 1);
INSERT INTO `ref_pays` VALUES(104, 'NO', 'NOR', 'Norvège', 7, 'BEOM', 'Nord', 'Elevé', 'couronne norvégienne', 1);
INSERT INTO `ref_pays` VALUES(105, 'NL', 'NLD', 'Pays-Bas', 7, 'BEOM', 'Nord', 'Elevé', 'euro', 1);
INSERT INTO `ref_pays` VALUES(106, 'NI', 'NIC', 'Nicaragua', 3, 'BA', 'Sud', 'Moyen', 'cordoba', 1);
INSERT INTO `ref_pays` VALUES(107, 'NG', 'NGA', 'Nigéria', 2, 'BAO', 'Sud', 'Faible', 'naira', 1);
INSERT INTO `ref_pays` VALUES(108, 'NE', 'NER', 'Niger', 2, 'BAO', 'Sud', 'Faible', 'franc C.F.A.', 1);
INSERT INTO `ref_pays` VALUES(109, 'NA', 'NAM', 'Namibie', 1, 'BAC', 'Sud', 'Moyen', '"dollar de Namibie', 1);
INSERT INTO `ref_pays` VALUES(110, 'MZ', 'MOZ', 'Mozambique', 9, 'BOI', 'Sud', 'Faible', 'metical', 1);
INSERT INTO `ref_pays` VALUES(111, 'MY', 'MYS', 'Malaisie', 4, 'BAP', 'Sud', 'Moyen', 'ringgit', 1);
INSERT INTO `ref_pays` VALUES(112, 'MX', 'MEX', 'Mexique', 3, 'BA', 'Sud', 'Moyen', 'None', 1);
INSERT INTO `ref_pays` VALUES(113, 'MW', 'MWI', 'Malawi', 1, 'BAC', 'Sud', 'Faible', 'kwacha du Malawi', 1);
INSERT INTO `ref_pays` VALUES(114, 'MV', 'MDV', 'Maldives', 4, 'BAP', 'Sud', 'Moyen', 'rufiyaa', 1);
INSERT INTO `ref_pays` VALUES(115, 'MU', 'MUS', 'Maurice', 9, 'BOI', 'Sud', 'Moyen', 'roupie mauricienne', 1);
INSERT INTO `ref_pays` VALUES(116, 'MT', 'MLT', 'Malte', 7, 'BEOM', 'Nord', 'Elevé', 'lire maltaise', 1);
INSERT INTO `ref_pays` VALUES(117, 'MR', 'MRT', 'Mauritanie', 2, 'BAO', 'Sud', 'Faible', 'ouguiya', 1);
INSERT INTO `ref_pays` VALUES(118, 'MN', 'MNG', 'Mongolie', 6, 'BECO', 'Sud', 'Moyen', 'tugrik', 1);
INSERT INTO `ref_pays` VALUES(119, 'MM', 'MMR', 'Myanmar', 4, 'BAP', 'Sud', 'Faible', 'kyat', 1);
INSERT INTO `ref_pays` VALUES(120, 'ML', 'MLI', 'Mali', 2, 'BAO', 'Sud', 'Faible', 'Un peuple, un but, une foi', 1);
INSERT INTO `ref_pays` VALUES(121, 'MK', 'MKD', 'Macédoine, l''ex-république yougoslave de', 6, 'BECO', 'Sud', 'Moyen', 'denar', 1);
INSERT INTO `ref_pays` VALUES(122, 'MH', 'MHL', 'Marshall, îles', 4, 'BAP', 'Sud', 'Moyen', 'dollar US', 1);
INSERT INTO `ref_pays` VALUES(123, 'MD', 'MDA', 'Moldova', 6, 'BECO', 'Sud', 'Moyen', 'leu moldave', 1);
INSERT INTO `ref_pays` VALUES(124, 'MG', 'MDG', 'Madagascar', 9, 'BOI', 'Sud', 'Faible', 'franc malgache', 1);
INSERT INTO `ref_pays` VALUES(125, 'MC', 'MCO', 'Monaco', 7, 'BEOM', 'Nord', 'Elevé', 'euro', 1);
INSERT INTO `ref_pays` VALUES(126, 'MA', 'MAR', 'Maroc', 7, 'BEOM', 'Sud', 'Moyen', 'dirham marocain', 1);
INSERT INTO `ref_pays` VALUES(127, 'LY', 'LBY', 'Libyenne, jamahiriya arabe', 1, 'BAC', 'Sud', 'Moyen', 'dinar libyen', 1);
INSERT INTO `ref_pays` VALUES(128, 'LV', 'LVA', 'Lettonie', 6, 'BECO', 'Sud', 'Moyen', 'lats', 1);
INSERT INTO `ref_pays` VALUES(129, 'LU', 'LUX', 'Luxembourg', 7, 'BEOM', 'Nord', 'Elevé', 'euro', 1);
INSERT INTO `ref_pays` VALUES(130, 'LS', 'LSO', 'Lesotho', 1, 'BAC', 'Sud', 'Moyen', 'loti', 1);
INSERT INTO `ref_pays` VALUES(131, 'LT', 'LTU', 'Lituanie', 6, 'BECO', 'Sud', 'Moyen', 'litas', 1);
INSERT INTO `ref_pays` VALUES(132, 'LR', 'LBR', 'Libéria', 2, 'BAO', 'Sud', 'Faible', 'dollar libérien', 1);
INSERT INTO `ref_pays` VALUES(133, 'LK', 'LKA', 'Sri Lanka', 4, 'BAP', 'Sud', 'Moyen', 'roupie sri-lankaise', 1);
INSERT INTO `ref_pays` VALUES(134, 'LI', 'LIE', 'Liechtenstein', 7, 'BEOM', 'Nord', 'Elevé', 'franc suisse', 1);
INSERT INTO `ref_pays` VALUES(135, 'LC', 'LCA', 'Sainte-Lucie', 5, 'BC', 'Sud', 'Moyen', 'dollar des Caraïbes de l''Est', 1);
INSERT INTO `ref_pays` VALUES(136, 'LB', 'LBN', 'Liban', 8, 'BMO', 'Sud', 'Moyen', 'livre libanaise', 1);
INSERT INTO `ref_pays` VALUES(137, 'LA', 'LAO', 'Lao, république démocratique populaire', 4, 'BAP', 'Sud', 'Faible', 'kip', 1);
INSERT INTO `ref_pays` VALUES(138, 'KZ', 'KAZ', 'Kazakhstan', 6, 'BECO', 'Sud', 'Moyen', 'tenge', 1);
INSERT INTO `ref_pays` VALUES(139, 'KW', 'KWT', 'Koweït', 8, 'BMO', 'Nord', 'Elevé', 'dinar koweïtien', 1);
INSERT INTO `ref_pays` VALUES(140, 'KR', 'KOR', 'Corée, république de', 4, 'BAP', 'Nord', 'Elevé', 'won sud-coréen', 1);
INSERT INTO `ref_pays` VALUES(141, 'KP', 'PRK', 'Corée, république populaire démocratique de', 4, 'BAP', 'Sud', 'Faible', 'won nord-coréen', 1);
INSERT INTO `ref_pays` VALUES(142, 'KM', 'COM', 'Comores', 9, 'BOI', 'Sud', 'Faible', 'franc des Comores', 1);
INSERT INTO `ref_pays` VALUES(143, 'KN', 'KNA', 'Saint-Kitts-et-Nevis', 5, 'BC', 'Sud', 'Moyen', 'dollar des Caraïbes de l''Est', 1);
INSERT INTO `ref_pays` VALUES(144, 'KI', 'KIR', 'Kiribati', 4, 'BAP', 'Sud', 'Moyen', 'dollar australien', 1);
INSERT INTO `ref_pays` VALUES(145, 'KH', 'KHM', 'Cambodge', 4, 'BAP', 'Sud', 'Faible', 'riel', 1);
INSERT INTO `ref_pays` VALUES(146, 'KG', 'KGZ', 'Kirghizistan', 6, 'BECO', 'Sud', 'Faible', 'som', 1);
INSERT INTO `ref_pays` VALUES(147, 'KE', 'KEN', 'Kenya', 9, 'BOI', 'Sud', 'Faible', 'shilling kényan', 1);
INSERT INTO `ref_pays` VALUES(148, 'JP', 'JPN', 'Japon', 4, 'BAP', 'Nord', 'Elevé', 'yen', 1);
INSERT INTO `ref_pays` VALUES(149, 'JO', 'JOR', 'Jordanie', 8, 'BMO', 'Sud', 'Moyen', 'dinar jordanien', 1);
INSERT INTO `ref_pays` VALUES(150, 'JM', 'JAM', 'Jamaïque', 5, 'BC', 'Sud', 'Moyen', 'dollar jamaïquain', 1);
INSERT INTO `ref_pays` VALUES(151, 'IT', 'ITA', 'Italie', 7, 'BEOM', 'Nord', 'Elevé', 'euro', 1);
INSERT INTO `ref_pays` VALUES(152, 'IS', 'ISL', 'Islande', 7, 'BEOM', 'Nord', 'Elevé', 'couronne islandaise', 1);
INSERT INTO `ref_pays` VALUES(153, 'IR', 'IRN', 'Iran, république islamique d''', 8, 'BMO', 'Sud', 'Moyen', 'rial iranien', 1);
INSERT INTO `ref_pays` VALUES(154, 'IQ', 'IRQ', 'Iraq', 8, 'BMO', 'Sud', 'Moyen', 'dinar iraquien', 1);
INSERT INTO `ref_pays` VALUES(155, 'IN', 'IND', 'Inde', 4, 'BAP', 'Sud', 'Moyen', 'La vérité l''emportera.', 1);
INSERT INTO `ref_pays` VALUES(156, 'IL', 'ISR', 'Israël', 7, 'BEOM', 'Nord', 'Elevé', 'nouveau shekel', 1);
INSERT INTO `ref_pays` VALUES(157, 'IE', 'IRL', 'Irlande', 7, 'BEOM', 'Nord', 'Elevé', 'euro', 1);
INSERT INTO `ref_pays` VALUES(158, 'ID', 'IDN', 'Indonésie', 4, 'BAP', 'Sud', 'Moyen', 'rupiah indonésienne', 1);
INSERT INTO `ref_pays` VALUES(159, 'HU', 'HUN', 'Hongrie', 6, 'BECO', 'Nord', 'Elevé', 'forint', 1);
INSERT INTO `ref_pays` VALUES(160, 'HT', 'HTI', 'Haïti', 5, 'BC', 'Sud', 'Faible', 'L''union fait la force."', 1);
INSERT INTO `ref_pays` VALUES(161, 'HR', 'HRV', 'Croatie', 6, 'BECO', 'Sud', 'Moyen', 'kuna', 1);
INSERT INTO `ref_pays` VALUES(162, 'HN', 'HND', 'Honduras', 3, 'BA', 'Sud', 'Moyen', 'lempira', 1);
INSERT INTO `ref_pays` VALUES(163, 'GY', 'GUY', 'Guyana', 3, 'BA', 'Sud', 'Moyen', 'dollar de Guyana', 1);
INSERT INTO `ref_pays` VALUES(164, 'GW', 'GNB', 'Guinée-Bissau', 2, 'BAO', 'Sud', 'Faible', 'franc C.F.A.', 1);
INSERT INTO `ref_pays` VALUES(165, 'GT', 'GTM', 'Guatemala', 3, 'BA', 'Sud', 'Moyen', 'quetzal', 1);
INSERT INTO `ref_pays` VALUES(166, 'GR', 'GRC', 'Grèce', 7, 'BEOM', 'Nord', 'Elevé', 'euro', 1);
INSERT INTO `ref_pays` VALUES(167, 'GQ', 'GNQ', 'Guinée équatoriale', 1, 'BAC', 'Nord', 'Elevé', 'franc C.F.A.', 1);
INSERT INTO `ref_pays` VALUES(168, 'GN', 'GIN', 'Guinée', 2, 'BAO', 'Sud', 'Faible', 'franc guinéen', 1);
INSERT INTO `ref_pays` VALUES(169, 'GM', 'GMB', 'Gambie', 2, 'BAO', 'Sud', 'Faible', 'dalasi', 1);
INSERT INTO `ref_pays` VALUES(170, 'GH', 'GHA', 'Ghana', 2, 'BAO', 'Sud', 'Faible', 'cedi', 1);
INSERT INTO `ref_pays` VALUES(171, 'GE', 'GEO', 'Géorgie', 6, 'BECO', 'Sud', 'Moyen', 'lari', 1);
INSERT INTO `ref_pays` VALUES(172, 'GD', 'GRD', 'Grenade', 5, 'BC', 'Sud', 'Moyen', 'dollar des Caraïbes de l''Est', 1);
INSERT INTO `ref_pays` VALUES(173, 'GB', 'GBR', 'Royaume-Uni', 7, 'BEOM', 'Nord', 'Elevé', 'livre sterling', 1);
INSERT INTO `ref_pays` VALUES(174, 'G3', 'G33', 'Général', 0, 'BSC', 'None', 'inconnu', 'None', 1);
INSERT INTO `ref_pays` VALUES(175, 'GA', 'GAB', 'Gabon', 1, 'BAC', 'Sud', 'Moyen', 'franc C.F.A.', 1);
INSERT INTO `ref_pays` VALUES(176, 'FR', 'FRA', 'France', 7, 'BEOM', 'Nord', 'Elevé', 'euro', 1);
INSERT INTO `ref_pays` VALUES(177, 'FM', 'FSM', 'Micronésie, états fédérés de', 4, 'BAP', 'Sud', 'Moyen', 'dollar US', 1);
INSERT INTO `ref_pays` VALUES(178, 'FJ', 'FJI', 'Fidji', 4, 'BAP', 'Sud', 'Moyen', 'dollar des Fidji', 1);
INSERT INTO `ref_pays` VALUES(179, 'FI', 'FIN', 'Finlande', 7, 'BEOM', 'Nord', 'Elevé', 'euro', 1);
INSERT INTO `ref_pays` VALUES(180, 'ET', 'ETH', 'Éthiopie', 1, 'BAC', 'Sud', 'Faible', 'birr éthiopien', 1);
INSERT INTO `ref_pays` VALUES(181, 'ER', 'ERI', 'Érythrée', 1, 'BAC', 'Sud', 'Faible', 'nakfa', 1);
INSERT INTO `ref_pays` VALUES(182, 'ES', 'ESP', 'Espagne', 7, 'BEOM', 'Nord', 'Elevé', 'euro', 1);
INSERT INTO `ref_pays` VALUES(183, 'EG', 'EGY', 'Égypte', 8, 'BMO', 'Sud', 'Moyen', 'livre égyptienne', 1);
INSERT INTO `ref_pays` VALUES(184, 'EC', 'ECU', 'Équateur', 3, 'BA', 'Sud', 'Moyen', 'dollar US', 1);
INSERT INTO `ref_pays` VALUES(185, 'EE', 'EST', 'Estonie', 6, 'BECO', 'Nord', 'Elevé', 'couronne estonienne', 1);
INSERT INTO `ref_pays` VALUES(186, 'VA', 'VAT', 'Saint-Siège (État de la Cité du Vatican)', 7, 'BEOM', 'Nord', 'Elevé', 'euro', 1);
INSERT INTO `ref_pays` VALUES(187, 'VC', 'VCT', 'Saint-Vincent-Et-Les Grenadines', 5, 'BC', 'Sud', 'Moyen', 'dollar des Caraïbes de l''Est', 1);
INSERT INTO `ref_pays` VALUES(188, 'VE', 'VEN', 'Venezuela', 3, 'BA', 'Sud', 'Moyen', 'bolivar', 1);
INSERT INTO `ref_pays` VALUES(189, 'VN', 'VNM', 'Viet Nam', 4, 'BAP', 'Sud', 'Faible', 'dông', 1);
INSERT INTO `ref_pays` VALUES(190, 'VU', 'VUT', 'Vanuatu', 4, 'BAP', 'Sud', 'Moyen', 'vatu', 1);
INSERT INTO `ref_pays` VALUES(191, 'WS', 'WSM', 'Samoa', 4, 'BAP', 'Sud', 'Moyen', 'tala', 1);
INSERT INTO `ref_pays` VALUES(192, 'YE', 'YEM', 'Yémen', 8, 'BMO', 'Sud', 'Faible', 'riyal yéménite', 1);
INSERT INTO `ref_pays` VALUES(193, 'ZA', 'ZAF', 'Afrique du Sud', 9, 'BOI', 'Sud', 'Moyen', 'L''union fait la force (Ex Unitate Vires)', 1);
INSERT INTO `ref_pays` VALUES(194, 'ZM', 'ZMB', 'Zambie', 1, 'BAC', 'Sud', 'Faible', 'Kwacha de Zambie', 1);
INSERT INTO `ref_pays` VALUES(195, 'ZW', 'ZWE', 'Zimbabwe', 1, 'BAC', 'Sud', 'Faible', 'dollar du Zimbabwe', 1);
INSERT INTO `ref_pays` VALUES(196, 'RS', 'SRB', 'Serbie', 6, 'BECO', 'Sud', 'Moyen', 'dinar yougoslave', 1);
INSERT INTO `ref_pays` VALUES(197, 'ME', 'MNE', 'Monténégro', 6, 'BECO', 'Sud', 'Moyen', 'dinar yougoslave', 1);

