

INSERT INTO `ref_poste` VALUES(1, 'EX', 'Ecarts de change', '', 1);
INSERT INTO `ref_poste` VALUES(2, 'AA', 'Générique', '', 1);
INSERT INTO `ref_poste` VALUES(3, 'AD', 'Achats documentaires', '', 1);
INSERT INTO `ref_poste` VALUES(4, 'AF', 'Appel à candidatures, appel d''offres', '', 1);
INSERT INTO `ref_poste` VALUES(5, 'AG', 'Assemblée générale', '', 1);
INSERT INTO `ref_poste` VALUES(6, 'AJ', 'Ajustement budgétaire', '', 1);
INSERT INTO `ref_poste` VALUES(7, 'AN', 'Animation / Coordination', '', 1);
INSERT INTO `ref_poste` VALUES(8, 'AP', 'Année préparatoire', '', 1);
INSERT INTO `ref_poste` VALUES(9, 'AQ', 'Accompagnement Sommet', '', 1);
INSERT INTO `ref_poste` VALUES(10, 'AR', 'Animation régionale', '', 1);
INSERT INTO `ref_poste` VALUES(11, 'BB', 'Réseau des bibliothèques sc. franc.', '', 1);
INSERT INTO `ref_poste` VALUES(12, 'BD', 'Accès aux banques de données', '', 1);
INSERT INTO `ref_poste` VALUES(13, 'BE', 'Bourses étudiants', '', 1);
INSERT INTO `ref_poste` VALUES(14, 'BF', 'Bulletin des études françaises', '', 1);
INSERT INTO `ref_poste` VALUES(15, 'BL', 'Mobilités Stages linguistiques', '', 1);
INSERT INTO `ref_poste` VALUES(16, 'BM', 'Mobilités Mali-Paris 8', '', 1);
INSERT INTO `ref_poste` VALUES(17, 'BR', 'Réunion des Directeurs de Bureau', '', 1);
INSERT INTO `ref_poste` VALUES(18, 'BS', 'Banques de données en Sc. Sociales', '', 1);
INSERT INTO `ref_poste` VALUES(19, 'BX', 'Mobilité de réseaux scientifiques et associatifs', 'Mobilités', 1);
INSERT INTO `ref_poste` VALUES(20, 'CA', 'Conseil d''Administration', '', 1);
INSERT INTO `ref_poste` VALUES(21, 'CB', 'Incubateurs', '', 1);
INSERT INTO `ref_poste` VALUES(22, 'CC', 'Commission CAMES/CRUFAOCI', '', 1);
INSERT INTO `ref_poste` VALUES(23, 'CD', 'Centre de documentation', '', 1);
INSERT INTO `ref_poste` VALUES(24, 'CE', 'Conseil permanent de la Francophonie', '', 1);
INSERT INTO `ref_poste` VALUES(25, 'CG', 'Comité de gestion', '', 1);
INSERT INTO `ref_poste` VALUES(26, 'CH', 'Edition de Cahiers de recherche', '', 1);
INSERT INTO `ref_poste` VALUES(27, 'CM', 'Appui à la commission', '', 1);
INSERT INTO `ref_poste` VALUES(28, 'CN', 'Conseil Associatif', '', 1);
INSERT INTO `ref_poste` VALUES(29, 'CQ', 'Colloques, Séminaires', '', 1);
INSERT INTO `ref_poste` VALUES(30, 'CR', 'Comité de réseau', '', 1);
INSERT INTO `ref_poste` VALUES(31, 'CS', 'Conseil Scientifique', '', 1);
INSERT INTO `ref_poste` VALUES(32, 'CT', 'Communication', '', 1);
INSERT INTO `ref_poste` VALUES(33, 'CU', 'Consortium', '', 1);
INSERT INTO `ref_poste` VALUES(34, 'DF', 'Réseau des DEF', '', 1);
INSERT INTO `ref_poste` VALUES(35, 'DG', 'Dotation pédagogique et logistique', '', 1);
INSERT INTO `ref_poste` VALUES(36, 'DM', 'CAMES Médecine', '', 1);
INSERT INTO `ref_poste` VALUES(37, 'DP', 'Documents primaires', '', 1);
INSERT INTO `ref_poste` VALUES(38, 'DR', 'Codirection de thèse', '', 1);
INSERT INTO `ref_poste` VALUES(39, 'DS', 'Droits d''inscription', '', 1);
INSERT INTO `ref_poste` VALUES(40, 'DT', 'Développements', '', 1);
INSERT INTO `ref_poste` VALUES(41, 'EC', 'Editorial et contenus', '', 1);
INSERT INTO `ref_poste` VALUES(42, 'ED', 'Edition institutionnel', '', 1);
INSERT INTO `ref_poste` VALUES(43, 'EF', 'Espaces francophones', '', 1);
INSERT INTO `ref_poste` VALUES(44, 'EG', 'Edition d''ouvrages, manuels', '', 1);
INSERT INTO `ref_poste` VALUES(45, 'EL', 'Edition en ligne', '', 1);
INSERT INTO `ref_poste` VALUES(46, 'EN', 'Encadrement', '', 1);
INSERT INTO `ref_poste` VALUES(47, 'EQ', 'Equipement et logistique (progr.)', '', 0);
INSERT INTO `ref_poste` VALUES(48, 'ET', 'Recrutement étudiants', '', 1);
INSERT INTO `ref_poste` VALUES(49, 'EV', 'Enveloppe inter-régionale', '', 1);
INSERT INTO `ref_poste` VALUES(50, 'FA', 'Formation à distance', '', 1);
INSERT INTO `ref_poste` VALUES(51, 'FC', 'Création filières', '', 1);
INSERT INTO `ref_poste` VALUES(52, 'FE', 'Formation pédagogique', '', 1);
INSERT INTO `ref_poste` VALUES(53, 'FF', 'Formation des formateurs', '', 1);
INSERT INTO `ref_poste` VALUES(54, 'FH', 'Form. Administrat° Système et Réseau', '', 1);
INSERT INTO `ref_poste` VALUES(55, 'FJ', 'Formation Systèmes d''Information', '', 1);
INSERT INTO `ref_poste` VALUES(56, 'FK', 'Formation Technologies éducatives', '', 1);
INSERT INTO `ref_poste` VALUES(57, 'FL', 'Formation linguistique', '', 1);
INSERT INTO `ref_poste` VALUES(58, 'FM', 'Français médical', '', 1);
INSERT INTO `ref_poste` VALUES(59, 'FR', 'Bourse de doctorat', 'Mobilités', 1);
INSERT INTO `ref_poste` VALUES(60, 'FS', 'Formation scientifique', '', 1);
INSERT INTO `ref_poste` VALUES(61, 'FT', 'Appui au fonctionnement', '', 1);
INSERT INTO `ref_poste` VALUES(62, 'FU', 'CAMES Droit', '', 1);
INSERT INTO `ref_poste` VALUES(63, 'FW', 'Formation permanente', '', 1);
INSERT INTO `ref_poste` VALUES(64, 'FX', 'Bourse de formation initiale', 'Mobilités', 1);
INSERT INTO `ref_poste` VALUES(65, 'FZ', 'Formation aux TI', '', 0);
INSERT INTO `ref_poste` VALUES(66, 'GN', 'Genet', '', 1);
INSERT INTO `ref_poste` VALUES(67, 'GS', 'Frais de gestion', '', 1);
INSERT INTO `ref_poste` VALUES(68, 'JC', 'Prix Jeunes Chercheurs', '', 0);
INSERT INTO `ref_poste` VALUES(69, 'JY', 'Jury', '', 1);
INSERT INTO `ref_poste` VALUES(70, 'KA', 'Cursus - DEA informatique', '', 1);
INSERT INTO `ref_poste` VALUES(71, 'KB', 'Cursus - DESS en ethno-psychiatrie', '', 1);
INSERT INTO `ref_poste` VALUES(72, 'KC', 'Cursus - Médecine tropicale', '', 1);
INSERT INTO `ref_poste` VALUES(73, 'KD', 'Cursus - Droits fondamentaux', '', 1);
INSERT INTO `ref_poste` VALUES(74, 'KE', 'Cursus - Droit int. de l''environnemt', '', 1);
INSERT INTO `ref_poste` VALUES(75, 'KF', 'Cursus - Eveil (maitrise finances)', '', 1);
INSERT INTO `ref_poste` VALUES(76, 'KG', 'Cursus - Mastère en agro-management', '', 1);
INSERT INTO `ref_poste` VALUES(77, 'KH', 'Cursus - Licence en chimie', '', 1);
INSERT INTO `ref_poste` VALUES(78, 'KL', 'Cursus en ligne', '', 1);
INSERT INTO `ref_poste` VALUES(79, 'KM', 'Cursus - Management international', '', 1);
INSERT INTO `ref_poste` VALUES(80, 'KN', 'Cursus - Partenariat AO avec MENRT', '', 1);
INSERT INTO `ref_poste` VALUES(81, 'KP', 'Cursus - Licence métiers internet', '', 1);
INSERT INTO `ref_poste` VALUES(82, 'KQ', 'Cursus - Partenariat Teluq', '', 1);
INSERT INTO `ref_poste` VALUES(83, 'KT', 'Cursus - Maladies parasitaires trop.', '', 1);
INSERT INTO `ref_poste` VALUES(84, 'KU', 'Cursus - DESS UTICE', '', 1);
INSERT INTO `ref_poste` VALUES(85, 'KX', 'Cursus - Etudes et expérimentations', '', 1);
INSERT INTO `ref_poste` VALUES(86, 'LC', 'Indemnités locales', '', 1);
INSERT INTO `ref_poste` VALUES(87, 'LD', 'Linux - Développement', '', 1);
INSERT INTO `ref_poste` VALUES(88, 'LE', 'Indemnités enseignants', '', 1);
INSERT INTO `ref_poste` VALUES(89, 'LF', 'Linux - Formation', '', 1);
INSERT INTO `ref_poste` VALUES(90, 'LG', 'Logistique', '', 1);
INSERT INTO `ref_poste` VALUES(91, 'LS', 'Linux - Sensibilisation', '', 1);
INSERT INTO `ref_poste` VALUES(92, 'MD', 'Modules d''enseignement multimédia', '', 1);
INSERT INTO `ref_poste` VALUES(93, 'ME', 'Mission d''appui et d''enseignement', 'Mobilités', 1);
INSERT INTO `ref_poste` VALUES(94, 'MF', 'Conférence ministérielle de la Fr.', '', 1);
INSERT INTO `ref_poste` VALUES(95, 'MM', 'Mémoires en français', '', 1);
INSERT INTO `ref_poste` VALUES(96, 'MP', 'Micro projets', '', 1);
INSERT INTO `ref_poste` VALUES(97, 'MX', 'Intervenants manifestations francop.', '', 0);
INSERT INTO `ref_poste` VALUES(98, 'ND', 'NTE déploiement', '', 1);
INSERT INTO `ref_poste` VALUES(99, 'NT', 'Observatoire éthique NT', '', 1);
INSERT INTO `ref_poste` VALUES(100, 'PA', 'Création de points d''accès', '', 1);
INSERT INTO `ref_poste` VALUES(101, 'PB', 'Prix scientifique de la Francophonie', '', 1);
INSERT INTO `ref_poste` VALUES(102, 'PC', 'Premier cycle sur mesure (PCSM)', '', 1);
INSERT INTO `ref_poste` VALUES(103, 'PE', 'Frais pédagogiques', '', 1);
INSERT INTO `ref_poste` VALUES(104, 'PF', 'Bourse de perfectionnement en formation', 'Mobilités', 1);
INSERT INTO `ref_poste` VALUES(105, 'PG', 'Conception pédagogique', '', 1);
INSERT INTO `ref_poste` VALUES(106, 'PJ', 'Projet informatique', '', 1);
INSERT INTO `ref_poste` VALUES(107, 'PL', 'Conventions Pôles d''excellence', '', 1);
INSERT INTO `ref_poste` VALUES(108, 'PM', 'Promotion / publicité', '', 1);
INSERT INTO `ref_poste` VALUES(109, 'PN', 'Presse francophone', '', 1);
INSERT INTO `ref_poste` VALUES(110, 'PP', 'Bourse de post-doctorat', 'Mobilités', 1);
INSERT INTO `ref_poste` VALUES(111, 'PR', 'Bourse de perfectionnement en recherche (hors post-doc)', 'Mobilités', 1);
INSERT INTO `ref_poste` VALUES(112, 'PS', 'Conventions PCSI', '', 1);
INSERT INTO `ref_poste` VALUES(113, 'PU', 'Publications scientifiques', '', 1);
INSERT INTO `ref_poste` VALUES(114, 'PW', 'Passeport Internet', '', 1);
INSERT INTO `ref_poste` VALUES(115, 'PX', 'Prix El Fasi', '', 1);
INSERT INTO `ref_poste` VALUES(116, 'QB', 'Mobilier et éqpt non informatique', '', 1);
INSERT INTO `ref_poste` VALUES(117, 'QI', 'materiel informatique', '', 1);
INSERT INTO `ref_poste` VALUES(118, 'QR', 'Conventions Equipes de recherche', '', 1);
INSERT INTO `ref_poste` VALUES(119, 'RB', 'Remboursement prêt', '', 1);
INSERT INTO `ref_poste` VALUES(120, 'RC', 'Réunion de constitution', '', 1);
INSERT INTO `ref_poste` VALUES(121, 'RF', 'Appui à la réforme', '', 1);
INSERT INTO `ref_poste` VALUES(122, 'RG', 'Regroupement pédagogique', '', 1);
INSERT INTO `ref_poste` VALUES(123, 'RM', 'Edition de cd-rom', '', 1);
INSERT INTO `ref_poste` VALUES(124, 'RQ', 'Rénovation et équipement (progr.)', '', 1);
INSERT INTO `ref_poste` VALUES(125, 'RR', 'Action de recherche en réseau', '', 1);
INSERT INTO `ref_poste` VALUES(126, 'RT', 'Réunions des instances', '', 1);
INSERT INTO `ref_poste` VALUES(127, 'RU', 'Réunions régionales', '', 1);
INSERT INTO `ref_poste` VALUES(128, 'RV', 'Edition de revues électroniques', '', 1);
INSERT INTO `ref_poste` VALUES(129, 'RX', 'IRENUCA', '', 1);
INSERT INTO `ref_poste` VALUES(130, 'RZ', 'Réserve', '', 1);
INSERT INTO `ref_poste` VALUES(131, 'SA', 'Services et abonnements', '', 1);
INSERT INTO `ref_poste` VALUES(132, 'SC', 'Bourse de stage culturel', 'Mobilités', 1);
INSERT INTO `ref_poste` VALUES(133, 'SD', 'Soutien au dispositif de français', '', 1);
INSERT INTO `ref_poste` VALUES(134, 'SE', 'Services et exploitation', '', 1);
INSERT INTO `ref_poste` VALUES(135, 'SF', 'Soutien filière didactique', '', 1);
INSERT INTO `ref_poste` VALUES(136, 'SG', 'Mobilités Stages terrain', '', 1);
INSERT INTO `ref_poste` VALUES(137, 'SM', 'Sommet', '', 1);
INSERT INTO `ref_poste` VALUES(138, 'SP', 'Bourse de stage professionnel', 'Mobilités', 1);
INSERT INTO `ref_poste` VALUES(139, 'SR', 'Aide à l''insertion professionnelle', '', 1);
INSERT INTO `ref_poste` VALUES(140, 'SS', 'Sociétés savantes', '', 1);
INSERT INTO `ref_poste` VALUES(141, 'ST', 'Stages linguistiques', '', 1);
INSERT INTO `ref_poste` VALUES(142, 'SU', 'Suivi, évaluation et expertise', '', 1);
INSERT INTO `ref_poste` VALUES(143, 'SX', 'Soutien au Ministère', '', 1);
INSERT INTO `ref_poste` VALUES(144, 'TA', 'Transfer - Algérie', '', 1);
INSERT INTO `ref_poste` VALUES(145, 'TB', 'Transfer - Bénin/Togo', '', 1);
INSERT INTO `ref_poste` VALUES(146, 'TC', 'Transfer - Bulgarie', '', 1);
INSERT INTO `ref_poste` VALUES(147, 'TD', 'Transfer déploiement', '', 1);
INSERT INTO `ref_poste` VALUES(148, 'TE', 'Transfer - Grands Lacs', '', 1);
INSERT INTO `ref_poste` VALUES(149, 'TF', 'Transfer - Cameroun', '', 1);
INSERT INTO `ref_poste` VALUES(150, 'TG', 'Transfer - Côte d''Ivoire', '', 1);
INSERT INTO `ref_poste` VALUES(151, 'TH', 'Transfer - Asie', '', 1);
INSERT INTO `ref_poste` VALUES(152, 'TI', 'Transfer - Guinée', '', 1);
INSERT INTO `ref_poste` VALUES(153, 'TJ', 'Transfer - Liban', '', 1);
INSERT INTO `ref_poste` VALUES(154, 'TK', 'Transfer - Liban/Syrie', '', 1);
INSERT INTO `ref_poste` VALUES(155, 'TL', 'Transfer - Madagascar', '', 1);
INSERT INTO `ref_poste` VALUES(156, 'TM', 'Transfer - Mali', '', 1);
INSERT INTO `ref_poste` VALUES(157, 'TN', 'Transfer - Maroc', '', 1);
INSERT INTO `ref_poste` VALUES(158, 'TP', 'Transfer - Tchad', '', 1);
INSERT INTO `ref_poste` VALUES(159, 'TQ', 'Transfer - Burkina/Niger', '', 1);
INSERT INTO `ref_poste` VALUES(160, 'TR', 'Transfer - Tunis/Algérie', '', 1);
INSERT INTO `ref_poste` VALUES(161, 'TS', 'Transfer - Congo', '', 1);
INSERT INTO `ref_poste` VALUES(162, 'TT', 'Transfer - Comores', '', 1);
INSERT INTO `ref_poste` VALUES(163, 'TU', 'Transfer - Tunisie', '', 1);
INSERT INTO `ref_poste` VALUES(164, 'TV', 'Transfer - Egypte/Liban', '', 1);
INSERT INTO `ref_poste` VALUES(165, 'TW', 'Transfer - Roumanie', '', 1);
INSERT INTO `ref_poste` VALUES(166, 'TX', 'Transfer - Haïti', '', 1);
INSERT INTO `ref_poste` VALUES(167, 'TY', 'Transfer - Maurice', '', 1);
INSERT INTO `ref_poste` VALUES(168, 'TZ', 'Transfer - Syrie', '', 1);
INSERT INTO `ref_poste` VALUES(169, 'X1', 'Ventilation budgétaire (DAFI) - Pr1', '', 1);
INSERT INTO `ref_poste` VALUES(170, 'X2', 'Ventilation budgétaire (DAFI) - Pr2', '', 1);
INSERT INTO `ref_poste` VALUES(171, 'X3', 'Ventilation budgétaire (DAFI) - Pr3', '', 1);
INSERT INTO `ref_poste` VALUES(172, 'X4', 'Ventilation budgétaire (DAFI) - Pr4', '', 1);
INSERT INTO `ref_poste` VALUES(173, 'X5', 'Ventilation budgétaire (DAFI) - Pr5', '', 1);
INSERT INTO `ref_poste` VALUES(174, 'X6', 'Ventilation budgétaire (DAFI) - Pr6', '', 1);
INSERT INTO `ref_poste` VALUES(175, 'X7', 'Ventilation budgétaire (DAFI) - Pr7', '', 1);
INSERT INTO `ref_poste` VALUES(176, 'X8', 'Ventilation budgétaire (DAFI) - Pr8', '', 1);
INSERT INTO `ref_poste` VALUES(177, 'XX', 'Ventilation budgétaire (DAFI)', '', 1);
INSERT INTO `ref_poste` VALUES(178, 'ZA', 'Contrat CIEE / Chicoutimi', '', 1);
INSERT INTO `ref_poste` VALUES(179, 'ZB', 'Contrat CIEE / Rimouski', '', 1);
INSERT INTO `ref_poste` VALUES(180, 'ZC', 'Contrat CIEE / Trois-Rivières', '', 1);
INSERT INTO `ref_poste` VALUES(181, 'ZD', 'Contrat Amb. Fr. Burundi', '', 1);
INSERT INTO `ref_poste` VALUES(182, 'ZE', 'Contrats de partenariats externes', '', 1);
INSERT INTO `ref_poste` VALUES(183, 'ZF', 'Contrat Ambassade de France Laos', '', 1);
INSERT INTO `ref_poste` VALUES(184, 'ZH', 'Contrat Ht Comissariat en Australie', '', 1);
INSERT INTO `ref_poste` VALUES(185, 'ZK', 'Contrat FOKAL', '', 1);
INSERT INTO `ref_poste` VALUES(186, 'ZL', 'Contrat IFAG / Leonardo', '', 1);
INSERT INTO `ref_poste` VALUES(187, 'ZM', 'Contrat CNF Bamako - Amb. France', '', 1);
INSERT INTO `ref_poste` VALUES(188, 'ZN', 'Contrat CAI Nouakchott - CyberForum', '', 1);
INSERT INTO `ref_poste` VALUES(189, 'ZP', 'Contrat Poitou-Charentes', '', 1);
INSERT INTO `ref_poste` VALUES(190, 'ZQ', 'Contrat Conseillers CSQ', '', 1);
INSERT INTO `ref_poste` VALUES(191, 'ZR', 'Contrat Rhones-Alpes', '', 1);
INSERT INTO `ref_poste` VALUES(192, 'ZS', 'Contrat SCAC - PNUD', '', 1);
INSERT INTO `ref_poste` VALUES(193, 'ZT', 'Contrat CAI Lomé - Amb. France', '', 1);
INSERT INTO `ref_poste` VALUES(194, 'ZU', 'Contrat CDU-CIUF', '', 1);
INSERT INTO `ref_poste` VALUES(195, 'ZV', 'Contrat Ambassade de France Vanuatu', '', 1);
INSERT INTO `ref_poste` VALUES(196, 'ZW', 'Contrat FFI', '', 1);
INSERT INTO `ref_poste` VALUES(197, 'ZX', 'Contrat FFI - CIRAD', '', 1);
INSERT INTO `ref_poste` VALUES(198, 'ZY', 'Contrat FFI - PRATIC OI', '', 1);
INSERT INTO `ref_poste` VALUES(199, 'ZZ', 'Contrat Collectivités locales', '', 1);
INSERT INTO `ref_poste` VALUES(200, 'FG', 'Cumul répartitions', '', 1);
INSERT INTO `ref_poste` VALUES(201, 'AS', 'Assurance locaux, matériel', '', 1);
INSERT INTO `ref_poste` VALUES(202, 'BC', 'Frs bancaires et de tenue de compte', '', 1);
INSERT INTO `ref_poste` VALUES(203, 'CF', 'Charges / Produits financiers', '', 1);
INSERT INTO `ref_poste` VALUES(204, 'CX', 'Charges / Produits exceptionnels', '', 1);
INSERT INTO `ref_poste` VALUES(205, 'DC', 'Documentation', '', 1);
INSERT INTO `ref_poste` VALUES(206, 'DV', 'Divers (à préciser)', '', 1);
INSERT INTO `ref_poste` VALUES(207, 'EM', 'Entretien, réparations, maintenance', '', 0);
INSERT INTO `ref_poste` VALUES(208, 'FB', 'Fournitures et petit équipement', '', 1);
INSERT INTO `ref_poste` VALUES(209, 'FN', 'Fournitures non stockables', '', 1);
INSERT INTO `ref_poste` VALUES(210, 'FP', 'Formation du personnel', '', 1);
INSERT INTO `ref_poste` VALUES(211, 'HV', 'Honoraires / vacations', '', 1);
INSERT INTO `ref_poste` VALUES(212, 'LY', 'Loyer', 'Mobilités', 1);
INSERT INTO `ref_poste` VALUES(213, 'MB', 'Mobilier / Équipement', '', 0);
INSERT INTO `ref_poste` VALUES(214, 'MG', 'Missions générales des perso. AUF', '', 1);
INSERT INTO `ref_poste` VALUES(215, 'PQ', 'Polycopies / Impression', '', 1);
INSERT INTO `ref_poste` VALUES(216, 'PT', 'Poste, télécommunications, internet', '', 1);
INSERT INTO `ref_poste` VALUES(217, 'RA', 'Dépenses d''opérations adm.', '', 1);
INSERT INTO `ref_poste` VALUES(218, 'RE', 'Relations extérieures', '', 1);
INSERT INTO `ref_poste` VALUES(219, 'RN', 'Travaux d''aménagement', '', 1);
INSERT INTO `ref_poste` VALUES(220, 'WP', 'Reports annuels', '', 1);
INSERT INTO `ref_poste` VALUES(221, 'WS', 'Réserve annuelle', '', 1);
INSERT INTO `ref_poste` VALUES(222, 'WE', 'payés Centralement Réserve', '', 1);
INSERT INTO `ref_poste` VALUES(223, 'WF', 'payés Localement Réserve', '', 1);
INSERT INTO `ref_poste` VALUES(224, 'WG', 'payés Centralement Report', '', 1);
INSERT INTO `ref_poste` VALUES(225, 'WH', 'payés Localement Report', '', 1);
INSERT INTO `ref_poste` VALUES(226, 'XC', 'payés Centralement Dotation', '', 1);
INSERT INTO `ref_poste` VALUES(227, 'XL', 'payés Localement Dotation', '', 1);
INSERT INTO `ref_poste` VALUES(228, '10', 'Yaoundé', '', 1);
INSERT INTO `ref_poste` VALUES(229, '11', 'Libreville', '', 1);
INSERT INTO `ref_poste` VALUES(230, '12', 'N''Djaména', '', 1);
INSERT INTO `ref_poste` VALUES(231, '13', 'Kinshasa', '', 1);
INSERT INTO `ref_poste` VALUES(232, '14', 'Bangui', '', 1);
INSERT INTO `ref_poste` VALUES(233, '15', 'Bujumbura', '', 1);
INSERT INTO `ref_poste` VALUES(234, '20', 'Dakar', '', 1);
INSERT INTO `ref_poste` VALUES(235, '21', 'Saint-Louis', '', 1);
INSERT INTO `ref_poste` VALUES(236, '22', 'Conakry', '', 1);
INSERT INTO `ref_poste` VALUES(237, '23', 'Nouakchott', '', 1);
INSERT INTO `ref_poste` VALUES(238, '24', 'Bamako', '', 1);
INSERT INTO `ref_poste` VALUES(239, '25', 'Ouagadougou', '', 1);
INSERT INTO `ref_poste` VALUES(240, '26', 'Niamey', '', 1);
INSERT INTO `ref_poste` VALUES(241, '27', 'Abidjan', '', 1);
INSERT INTO `ref_poste` VALUES(242, '28', 'Lomé', '', 1);
INSERT INTO `ref_poste` VALUES(243, '29', 'Cotonou', '', 1);
INSERT INTO `ref_poste` VALUES(244, '35', 'Port-au-Prince', '', 1);
INSERT INTO `ref_poste` VALUES(245, '36', 'Port-au-Prince IFGC', '', 1);
INSERT INTO `ref_poste` VALUES(246, '40', 'Hanoi', '', 1);
INSERT INTO `ref_poste` VALUES(247, '41', 'Danang/Hué', '', 1);
INSERT INTO `ref_poste` VALUES(248, '42', 'Hanoi IFI', '', 1);
INSERT INTO `ref_poste` VALUES(249, '43', 'Ho Chi Minh Ville', '', 1);
INSERT INTO `ref_poste` VALUES(250, '44', 'Ho Chi Minh Ville CAI', '', 1);
INSERT INTO `ref_poste` VALUES(251, '45', 'Vientiane', '', 1);
INSERT INTO `ref_poste` VALUES(252, '46', 'Vientiane IFMT', '', 1);
INSERT INTO `ref_poste` VALUES(253, '47', 'Phnom Penh', '', 1);
INSERT INTO `ref_poste` VALUES(254, '48', 'Phnom Penh ITC', '', 1);
INSERT INTO `ref_poste` VALUES(255, '49', 'Port-Vila', '', 1);
INSERT INTO `ref_poste` VALUES(256, '55', 'Beyrouth', '', 1);
INSERT INTO `ref_poste` VALUES(257, '56', 'Beyrouth CNF', '', 1);
INSERT INTO `ref_poste` VALUES(258, '65', 'Bucarest', '', 1);
INSERT INTO `ref_poste` VALUES(259, '66', 'Sofia IFAG', '', 1);
INSERT INTO `ref_poste` VALUES(260, '67', 'Chisinau', '', 1);
INSERT INTO `ref_poste` VALUES(261, '70', 'Antananarivo', '', 1);
INSERT INTO `ref_poste` VALUES(262, '71', 'Antananarivo CNF', '', 1);
INSERT INTO `ref_poste` VALUES(263, '72', 'Réduit IFE', '', 1);
INSERT INTO `ref_poste` VALUES(264, '73', 'Réduit', '', 1);
INSERT INTO `ref_poste` VALUES(265, '74', 'Moroni', '', 1);
INSERT INTO `ref_poste` VALUES(266, '80', 'Montréal Centrale', '', 1);
INSERT INTO `ref_poste` VALUES(267, '81', 'Montréal', '', 1);
INSERT INTO `ref_poste` VALUES(268, '82', 'Paris Centrale', '', 1);
INSERT INTO `ref_poste` VALUES(269, '83', 'Paris', '', 1);
INSERT INTO `ref_poste` VALUES(270, '84', 'Bruxelles', '', 1);
INSERT INTO `ref_poste` VALUES(271, '90', 'Rabat', '', 1);
INSERT INTO `ref_poste` VALUES(272, '91', 'Tunis', '', 1);
INSERT INTO `ref_poste` VALUES(273, '92', 'Alexandrie', '', 1);
INSERT INTO `ref_poste` VALUES(274, '93', 'Alexandrina', '', 1);
INSERT INTO `ref_poste` VALUES(275, '94', 'Alger', '', 1);
INSERT INTO `ref_poste` VALUES(276, 'C1', 'Central - P1', '', 1);
INSERT INTO `ref_poste` VALUES(277, 'C2', 'Central - P2', '', 1);
INSERT INTO `ref_poste` VALUES(278, 'C3', 'Central - P3', '', 1);
INSERT INTO `ref_poste` VALUES(279, 'C4', 'Central - P4', '', 1);
INSERT INTO `ref_poste` VALUES(280, 'C5', 'Central - P5', '', 1);
INSERT INTO `ref_poste` VALUES(281, 'C6', 'Central - P6', '', 1);
INSERT INTO `ref_poste` VALUES(282, 'C7', 'Central - P7', '', 1);
INSERT INTO `ref_poste` VALUES(283, 'C8', 'Central - P8', '', 1);
INSERT INTO `ref_poste` VALUES(284, 'GR', 'Poste général', '', 1);
INSERT INTO `ref_poste` VALUES(285, 'R1', 'Régional - P1', '', 1);
INSERT INTO `ref_poste` VALUES(286, 'R2', 'Régional - P2', '', 1);
INSERT INTO `ref_poste` VALUES(287, 'R3', 'Régional - P3', '', 1);
INSERT INTO `ref_poste` VALUES(288, 'R4', 'Régional - P4', '', 1);
INSERT INTO `ref_poste` VALUES(289, 'R5', 'Régional - P5', '', 1);
INSERT INTO `ref_poste` VALUES(290, 'R6', 'Régional - P6', '', 1);
INSERT INTO `ref_poste` VALUES(291, 'R7', 'Régional - P7', '', 1);
INSERT INTO `ref_poste` VALUES(292, 'R8', 'Régional - P8', '', 1);
INSERT INTO `ref_poste` VALUES(293, '99', 'Réserve', '', 1);
INSERT INTO `ref_poste` VALUES(294, '16', 'Brazzaville', '', 1);
INSERT INTO `ref_poste` VALUES(295, 'ER', 'Encadrant thèse recherche', '', 1);

